// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nXViDq22WPW4cpFn2ZHfzu_VaEkAYEs',
    appId: '1:280651104675:web:e7b062f71bbad0433cda16',
    messagingSenderId: '280651104675',
    projectId: 'opendoor-71af4',
    authDomain: 'opendoor-71af4.firebaseapp.com',
    storageBucket: 'opendoor-71af4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rw0n3PMuKbrLnapYL3EwBzh869xqS5o',
    appId: '1:280651104675:android:911ca840f5372f803cda16',
    messagingSenderId: '280651104675',
    projectId: 'opendoor-71af4',
    storageBucket: 'opendoor-71af4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKGHIDWCCsaRsRGzs5actsWRiytUcU6mg',
    appId: '1:280651104675:ios:743bb7cfa35bac673cda16',
    messagingSenderId: '280651104675',
    projectId: 'opendoor-71af4',
    storageBucket: 'opendoor-71af4.appspot.com',
    iosBundleId: 'com.example.openDors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKGHIDWCCsaRsRGzs5actsWRiytUcU6mg',
    appId: '1:280651104675:ios:428365477f81f9e33cda16',
    messagingSenderId: '280651104675',
    projectId: 'opendoor-71af4',
    storageBucket: 'opendoor-71af4.appspot.com',
    iosBundleId: 'com.example.openDors.RunnerTests',
  );
}
